### ISSUE TITLE
Blank Screen on Launch [bug]

### ISSUE THREAD

**Issue by lucas-chu** [arthyn/port#142]
**Bug Description*
After opening Port and launching a Comet, I click Open and get a blank screen.

<img width="1298" alt="image" src="https://user-images.githubusercontent.com/24814489/137589506-800e6044-e123-488c-aed6-9671b396b746.png">

**Expected Behavior**
I want to see home, where I can join Urbit chatrooms.

**Environment:**
 - OS: MacOS Big Sur
 - 
<img width="507" alt="image" src="https://user-images.githubusercontent.com/24814489/137589652-49c0d42e-dda7-4392-9b23-1c808b5189a2.png">
 - Port Version: 14.0

**Additional context**
Console errors:
1. 
Ship is not running or can't be contacted at port 12322
localhost:12322/:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
ipc.ts:73 1634391119933 "server received:" Object
ipc.ts:73 1634391119935 "server received:" Object
ipc.ts:73 1634391119936 "server received:" Object
ipc.ts:73 1634391119937 "server received:" Object
pier-service.ts:198 Ship is not running or can't be contacted.
ipc.ts:73 1634391119941 "server received:" Object
pier-service.ts:514 http: web interface live on http://localhost:8080

2. 
pier-service.ts:514 http: loopback live on http://localhost:12322

_http://localhost:8080/apps/grid/ isn't found and http://localhost:12322 leads me to:_
Internal Server Error

There was an error while handling the request for /.
/app/lens/hoon:<[62 18].[62 53]>
/app/lens/hoon:<[62 16].[62 53]>
/app/lens/hoon:<[62 3].[123 5]>
/app/lens/hoon:<[60 3].[123 5]>
/app/lens/hoon:<[59 3].[123 5]>
/app/lens/hoon:<[58 3].[123 5]>
/app/lens/hoon:<[56 3].[123 5]>
/app/lens/hoon:<[52 3].[123 5]>
/app/lens/hoon:<[50 3].[123 5]>
/sys/vane/gall/hoon:<[1.372 9].[1.372 37]>

3.
pier-service.ts:514 ; ~litzod not responding still trying
~millep_litzod:dojo> 
pier-service.ts:514 ; ~litzod is ok
~millep_litzod:dojo> 
pier-service.ts:514 ames: czar zod.urbit.org: ip .35.2

**Comment by lucas-chu** [comment]
Same blank screen with CLI
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/24814489/137590674-1cfa678f-c716-47e5-b097-d527e2ad3e25.png">

**Comment by lycurgus** [comment]
Sorry for the delay on this one, were you able to get it going?

If not - try running `:docket [%kick %garden]` in the CLI window (in your last screenshot there you should be able to hit backspace to get back to a prompt).

As an additional note, I think the failures with `content-length` are usually a result of an unstable internet connection. You may need to switch to a more stable connection if possible, while the system downloads the javascript assets.

**Comment by arthyn** [comment]
We checked this out at Assembly and thought maybe it was because of some unique network settings/security that he was running, but never got to revisit to nail down. @lucas-chu let us know if you're still seeing this, going to close until we hear back.

**Comment by raglep-ragret** [comment]
> Sorry for the delay on this one, were you able to get it going? If not - try running :docket [%kick %garden] in the CLI window (in your last screenshot there you should be able to hit backspace to get back to a prompt).

I'm not @lucas-chu, but I was also experiencing this same blank screen issue on Port (though on Windows). `:docket [%kick %garden]` immediately fixed it. Figured you might want confirmation that this suggestion can clear the issue.

Thank you. 👍
